package com.cookie.caskara;

import com.cookie.caskara.annotations.Id;
import com.cookie.caskara.exceptions.DatabaseException;
import org.junit.jupiter.api.*;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.CompletableFuture;

import static org.junit.jupiter.api.Assertions.*;

class EdgeCaseEntity {
    @Id
    private String privateId;
    public String data;

    public EdgeCaseEntity(String id, String data) {
        this.privateId = id;
        this.data = data;
    }
    
    public String getPrivateId() { return privateId; }
}

class InvalidFtsEntity {
    public String id;
    public String name;
}

public class ApiEdgeCaseTest {

    private File tempDbDir;

    @BeforeEach
    void setup() {
        tempDbDir = new File("test_edge_cases_db");
        tempDbDir.mkdirs();
        Caskara.init(tempDbDir);
    }

    @AfterEach
    void teardown() {
        Caskara.shutdown();
        deleteFolder(tempDbDir);
    }

    private void deleteFolder(File folder) {
        File[] files = folder.listFiles();
        if (files != null) {
            for (File f : files) {
                deleteFolder(f);
            }
        }
        folder.delete();
    }

    @Test
    @DisplayName("Query.search() throws DatabaseException when @FullTextSearch is missing")
    void testSearchWithoutFts() {
        assertThrows(DatabaseException.class, () -> {
            Caskara.query(InvalidFtsEntity.class).search("anything").fetch();
        });
    }

    @Test
    @DisplayName("Caskara.getId extracts private @Id field correctly")
    void testGetPrivateId() {
        EdgeCaseEntity entity = new EdgeCaseEntity("secret123", "value");
        String id = Caskara.getId(entity);
        assertEquals("secret123", id);
    }

    @Test
    @DisplayName("Caskara.save() auto-generates ID if field is null and no @Id is present")
    void testAutoGeneratedId() {
        InvalidFtsEntity entity = new InvalidFtsEntity();
        entity.name = "Test";
        String generatedId = Caskara.save(entity);
        
        assertNotNull(generatedId);
        assertNotEquals("", generatedId);
        
        InvalidFtsEntity loaded = Caskara.load(generatedId, InvalidFtsEntity.class);
        assertNotNull(loaded);
        assertEquals("Test", loaded.name);
    }

    @Test
    @DisplayName("Concurrent saves do not crash or corrupt data")
    void testConcurrentSaves() {
        List<CompletableFuture<Void>> futures = new ArrayList<>();
        
        for (int i = 0; i < 100; i++) {
            final int index = i;
            futures.add(CompletableFuture.runAsync(() -> {
                EdgeCaseEntity e = new EdgeCaseEntity("concurrent-" + index, "data " + index);
                Caskara.save(e);
            }));
        }
        
        CompletableFuture.allOf(futures.toArray(new CompletableFuture[0])).join();
        
        List<EdgeCaseEntity> all = Caskara.list(EdgeCaseEntity.class);
        assertEquals(100, all.size());
    }

    @Test
    @DisplayName("SaveAll with empty list does not fail")
    void testSaveAllEmpty() {
        List<EdgeCaseEntity> emptyList = new ArrayList<>();
        assertDoesNotThrow(() -> Caskara.saveAll(emptyList));
    }
    
    @Test
    @DisplayName("Caskara.load returns null for non-existent ID")
    void testLoadNonExistent() {
        EdgeCaseEntity loaded = Caskara.load("non-existent", EdgeCaseEntity.class);
        assertNull(loaded);
    }
}
